name: Bug Report
description: Report a problem with the game
title: "[BUG]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      
      validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - Linux
        - Android
        - iOS

  - type: input
    id: Version
    attributes:
      label: Application version

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
